      - name: Save and Push Images
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          
          # Paksa tambahkan folder finalplay
          git add finalplay/
          
          # Cek apakah ada perubahan (file baru)
          if git diff --cached --quiet; then
            echo "Tidak ada gambar baru untuk di-commit."
          else
            git commit -m "Simpan hasil foto AI ke finalplay [skip ci]"
            git push origin main
          fi
