name: Generate 10 Images
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update ke v4 juga untuk checkout

      - name: Set up Python
        uses: actions/setup-python@v5 # Update ke v5 untuk setup-python
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install google-generativeai

      - name: Run Generator
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python script.py

      - name: Upload Results
        uses: actions/upload-artifact@v4 # PERBAIKAN DI SINI (Ganti v3 ke v4)
        with:
          name: ai-images
          path: results/
          
